title: Dr. Kyra Rudy
email: kyra@u.northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Engineering Educator
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  jekyll
theme: minima
plugins:
  - jekyll-feed
